"""empty message

Revision ID: 1ee065c47aed
Revises: 52b9f2896502
Create Date: 2021-03-22 11:30:08.866482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ee065c47aed'
down_revision = '52b9f2896502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification', sa.Text(), nullable=True),
    sa.Column('sender', sa.String(length=64), nullable=True),
    sa.Column('notify_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # ### end Alembic commands ###
