"""empty message

Revision ID: bc72967cffb5
Revises: a9733c82fd0b
Create Date: 2021-02-22 13:41:40.763615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc72967cffb5'
down_revision = 'a9733c82fd0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('std_name', sa.String(length=64), nullable=True),
    sa.Column('f_name', sa.String(length=64), nullable=True),
    sa.Column('std_address', sa.String(length=128), nullable=True),
    sa.Column('std_contact', sa.String(length=64), nullable=True),
    sa.Column('std_class', sa.String(length=64), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_f_name'), 'student', ['f_name'], unique=False)
    op.create_index(op.f('ix_student_std_address'), 'student', ['std_address'], unique=False)
    op.create_index(op.f('ix_student_std_class'), 'student', ['std_class'], unique=False)
    op.create_index(op.f('ix_student_std_contact'), 'student', ['std_contact'], unique=False)
    op.create_index(op.f('ix_student_std_name'), 'student', ['std_name'], unique=False)
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tech_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('tech_address', sa.String(length=128), nullable=True),
    sa.Column('tech_contact', sa.String(length=64), nullable=True),
    sa.Column('tech_subject', sa.String(length=64), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_email'), 'teacher', ['email'], unique=False)
    op.create_index(op.f('ix_teacher_tech_address'), 'teacher', ['tech_address'], unique=False)
    op.create_index(op.f('ix_teacher_tech_contact'), 'teacher', ['tech_contact'], unique=False)
    op.create_index(op.f('ix_teacher_tech_name'), 'teacher', ['tech_name'], unique=False)
    op.create_index(op.f('ix_teacher_tech_subject'), 'teacher', ['tech_subject'], unique=False)
    op.create_table('worker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_name', sa.String(length=64), nullable=True),
    sa.Column('worker_address', sa.String(length=128), nullable=True),
    sa.Column('worker_contact', sa.String(length=64), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_worker_address'), 'worker', ['worker_address'], unique=False)
    op.create_index(op.f('ix_worker_worker_contact'), 'worker', ['worker_contact'], unique=False)
    op.create_index(op.f('ix_worker_worker_name'), 'worker', ['worker_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_worker_name'), table_name='worker')
    op.drop_index(op.f('ix_worker_worker_contact'), table_name='worker')
    op.drop_index(op.f('ix_worker_worker_address'), table_name='worker')
    op.drop_table('worker')
    op.drop_index(op.f('ix_teacher_tech_subject'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_tech_name'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_tech_contact'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_tech_address'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_email'), table_name='teacher')
    op.drop_table('teacher')
    op.drop_index(op.f('ix_student_std_name'), table_name='student')
    op.drop_index(op.f('ix_student_std_contact'), table_name='student')
    op.drop_index(op.f('ix_student_std_class'), table_name='student')
    op.drop_index(op.f('ix_student_std_address'), table_name='student')
    op.drop_index(op.f('ix_student_f_name'), table_name='student')
    op.drop_table('student')
    # ### end Alembic commands ###
