"""empty message

Revision ID: e93dc6d5b908
Revises: 
Create Date: 2021-03-17 10:53:42.979374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e93dc6d5b908'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cls_name', sa.String(length=64), nullable=True),
    sa.Column('cls_fee', sa.String(length=64), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave_worker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leave_worker_name', sa.String(length=64), nullable=True),
    sa.Column('leave_worker_address', sa.String(length=128), nullable=True),
    sa.Column('leave_worker_contact', sa.String(length=64), nullable=True),
    sa.Column('leave_date', sa.DateTime(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_name', sa.String(length=64), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_name', sa.String(length=64), nullable=True),
    sa.Column('worker_address', sa.String(length=128), nullable=True),
    sa.Column('worker_contact', sa.String(length=64), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave_student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('std_name', sa.String(length=64), nullable=True),
    sa.Column('f_name', sa.String(length=64), nullable=True),
    sa.Column('std_address', sa.String(length=128), nullable=True),
    sa.Column('std_contact', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=64), nullable=True),
    sa.Column('leave_date', sa.DateTime(), nullable=True),
    sa.Column('std_class', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['std_class'], ['class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave_teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tech_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('tech_address', sa.String(length=128), nullable=True),
    sa.Column('tech_contact', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=64), nullable=True),
    sa.Column('salary', sa.String(length=64), nullable=True),
    sa.Column('leave_date', sa.DateTime(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('tech_subject', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tech_subject'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('std_name', sa.String(length=64), nullable=True),
    sa.Column('f_name', sa.String(length=64), nullable=True),
    sa.Column('std_address', sa.String(length=128), nullable=True),
    sa.Column('std_contact', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=64), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.Column('std_class', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['std_class'], ['class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tech_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('tech_address', sa.String(length=128), nullable=True),
    sa.Column('tech_contact', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=64), nullable=True),
    sa.Column('salary', sa.String(length=64), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('tech_subject', sa.Integer(), nullable=True),
    sa.Column('tech_class', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tech_class'], ['class.id'], ),
    sa.ForeignKeyConstraint(['tech_subject'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload_lecture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('lecture', sa.Text(), nullable=True),
    sa.Column('img', sa.LargeBinary(), nullable=True),
    sa.Column('img_name', sa.String(length=64), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('teacher', sa.Integer(), nullable=True),
    sa.Column('tech_subject', sa.Integer(), nullable=True),
    sa.Column('tech_class', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher'], ['teacher.id'], ),
    sa.ForeignKeyConstraint(['tech_class'], ['class.id'], ),
    sa.ForeignKeyConstraint(['tech_subject'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_lecture')
    op.drop_table('teacher')
    op.drop_table('student')
    op.drop_table('leave_teacher')
    op.drop_table('leave_student')
    op.drop_table('worker')
    op.drop_table('subject')
    op.drop_table('leave_worker')
    op.drop_table('class')
    op.drop_table('user')
    # ### end Alembic commands ###
